examonline/urls.py
from django.urls import path
from . import views
urlpatterns=[
path('',views.home,name='home'),
path('home/admin',views.AdminHome,name='home-admin'),

###############  Teacher urls  ############### 
path('home/teacher',views.home_teacher,name='home-teacher'),
path('exam/create',views.ExamCreateView,name='exam-create'),
path('exam/<int:pk>/details',views.ExamDetailsView,name='exam-details'),
path('exam/<int:pk>/edit',views.ExamEditView,name='exam-edit'),
path('exam/<int:pk>/update',views.ExamUpdate,name='exam-update'),
path('exam/<int:pk>/post',views.ExamPost,name='exam-post'),
path('exam/<int:pk>/<int:spk>/solution',views.AnswerPaper,name='stud-solution'),
path('exam/<int:pk>/delete',views.ExamDeleteView,name='exam-delete'),
path('question/create',views.QuestionCreateView,name='question-create'),
path('question/<int:pk>/edit',views.QuestionEditView,name='question-edit'),
path('question/<int:pk>/option/create',views.OptionCreateView,name='option-create'),
path('question/<int:pk>/delete',views.QuestionDeleteView,name='question-delete'),
path('option/<int:pk>/correct',views.TrueOption,name='option-true'),
path('option/<int:pk>/delete',views.OptionDeleteView,name='option-delete'),
path('exam/<int:pk>/rank',views.Rank,name='exam-rank'),
path('exam/<int:pk>/passmark',views.PassMark,name='exam-pass'),
path('exam/<int:pk>/preview',views.ExamPreviewPaginated,name='exam-pag-preview'),

###############  Student urls  ############### 
path('home/student',views.home_student,name='home-student'),
path('exam/<int:pk>/guidelines',views.ExamGuidelinesView,name='exam-guidelines'),
path('exam/<int:pk>/attend',views.ExamAttend,name='exam-attend'),
path('exam/<int:pk>/solution/paginated',views.ExamSolutionPaginated,name='solution-paginated'),
path('exam/<int:pk>/submit',views.ExamSubmitView,name='exam-final-submit'),
path('exam/<int:pk>/confirm',views.ExamConfirmSubmit,name='exam-submit-confirmation'),
]

examproject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views as user_views 
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from examonline import views as exviews
urlpatterns = [
    path('',include('examonline.urls')),
    path('admin/', admin.site.urls),
    path('index',user_views.index,name='index'),
    path('register/teacher',user_views.teacher_registration,name='register-teacher'),
    path('register/student',user_views.student_registration,name='register-student'),
    path('login',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('password/update',user_views.change_password,name='password-change'),
    path('account',user_views.account,name='account'),
 
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
#if settings.DEBUG:
 #       urlpatterns += static(settings.MEDIA_URL,
  #                            document_root=settings.MEDIA_ROOT)

examonline/models.py
from django.db import models
from django.contrib.auth import get_user_model
from decimal import Decimal
User=get_user_model()
class Exam(models.Model):
	exam_creator=models.ForeignKey(User,on_delete=models.CASCADE)
	exam_name=models.CharField(max_length=255)
	exam_time=models.IntegerField(default=60)
	exam_marks=models.IntegerField(default=0)
	exam_ready=models.BooleanField(default=False)
	exam_passmark=models.IntegerField(default=1)
	def __str__(self):
		return self.exam_name
class Question(models.Model):
	question_exam=models.ForeignKey(Exam,on_delete=models.CASCADE)
	question=models.CharField(max_length =255,null=True,blank=True)
	question_creator=models.ForeignKey(User,on_delete=models.CASCADE)
	question_description=models.TextField(null=True,blank=True)
	markchoices=[(1,'1'),(2,'2')]
	negativechoices=[
	(0.00, 0.00),(Decimal("0.33"), '0.33'),
	(Decimal("0.66"), '0.66')
	]
	question_mark=models.IntegerField(choices=markchoices, default=1)
	question_negative=models.DecimalField(decimal_places=2, default=0.0, max_digits=3,choices=negativechoices)
	question_image=	models.ImageField(blank=True,null=True,upload_to="images/")
	def __str__(self):
		return ('Question from {}'.format(self.question_exam))
	
class Option(models.Model):
	question=models.ForeignKey(Question,on_delete=models.CASCADE)
	option=models.CharField(max_length=255)
	option_status=models.BooleanField(default=False)
	#option_exam=models.ForeignKey(Exam,on_delete=models.CASCADE)
	def __str__(self):
		return self.option
class Candidate(models.Model):
	stud_name=models.ForeignKey(User,on_delete=models.CASCADE)
	stud_exam=models.ForeignKey(Exam,on_delete=models.CASCADE)
	stud_question=models.ForeignKey(Question,on_delete=models.CASCADE)
	stud_option=models.ForeignKey(Option,on_delete=models.CASCADE)
	stud_mark=models.DecimalField(max_digits=3, decimal_places=2,default=0.00)
	def __str__(self):
		return ('{} by {}'.format(self.stud_question, self.stud_name))
class ExamStatus(models.Model):
	stud_name=models.ForeignKey(User,on_delete=models.CASCADE)
	test=models.ForeignKey(Exam,on_delete=models.CASCADE)
	exam_status=models.BooleanField(default=False)
	exam_marks=models.DecimalField(max_digits=5,decimal_places=2,default=0.00)
	rank=models.IntegerField(null=True,blank=True)
	timeleft=models.IntegerField(null=True,blank=True,default=0)
	def __str__(self):
		return ('{} by {} is {} '.format(self.test, self.stud_name,self.exam_status))

examonline/forms.py
from django import forms
from django.forms import ModelForm
from .models import Exam,Question,Option,Candidate

class ExamCreateForm(forms.ModelForm):
	class Meta:
		model=Exam
		fields=['exam_name','exam_time']
		labels = {
            'exam_time': ('Exam Time (in Minutes)'),
        }

class QuestionCreationForm(forms.ModelForm):
	class Meta:
		model=Question
		#fields='__all__'
		fields=['question','question_mark','question_negative','question_image']

class OptionCreationForm(forms.ModelForm):
	class Meta:
		model=Option
		fields=['option']

class ExamAttendForm(forms.ModelForm):
	stud_option=forms.ModelChoiceField(
		queryset=Option.objects.none(),
		widget=forms.RadioSelect(),
		required=False,	
		empty_label=None,label='Options')
	class Meta:
		model=Candidate
		fields=['stud_option']
class OptionUpdateForm(forms.ModelForm):
	class Meta:
		model=Candidate
		fields=['stud_option']

examonline/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from accounts.decorators import (user_is_teacher,user_is_student,
	user_is_examcreator,user_is_questioncreator,user_is_optioncreator)
from .models import Exam,Question,Option,Candidate,ExamStatus
from accounts.models import Student,User
from .forms import (ExamCreateForm,QuestionCreationForm,
	OptionCreationForm,ExamAttendForm,
	OptionUpdateForm)
from django.core.paginator import Paginator
from django.db.models import Sum
from itertools import chain
@login_required
def AdminHome(request):
	if request.user.is_superuser == True:
		exams=Exam.objects.all().order_by('exam_creator')
	else:
		raise PermissionDenied
	context={'exams':exams}
	return render (request,'examonline/adminhome.html',context)

@login_required
def home(request):
	if request.user.is_student == True:
		return redirect("/home/student")
	elif request.user.is_teacher==True: 
		return redirect("/home/teacher")
	return HttpResponse("Invalid")

###############  Teacher Views ############### 
@login_required
@user_is_teacher
def home_teacher(request):
	postedexams=Exam.objects.filter(exam_creator=request.user).filter(exam_ready=True)
	exams=Exam.objects.filter(exam_creator=request.user).filter(exam_ready=False)
	print(postedexams)
	print(exams)
	context={'postedexams':postedexams,'exams':exams}
	return render(request,"examonline/examslist.html",context)

@login_required
@user_is_teacher
def ExamCreateView(request):
	if request.method=='POST':	
		form=ExamCreateForm(request.POST)
		form.instance.exam_creator=request.user
		if form.is_valid():
			form.save()
		return redirect('/home/teacher')
	form=ExamCreateForm()
	context={'form':form}
	return render(request,'examonline/examcreate.html',context)

@login_required
@user_is_examcreator
def ExamDetailsView(request,pk):
	idd=pk
	Exam_Object=Exam.objects.get(pk=pk)
	questions=Question.objects.filter(question_exam=Exam_Object)
	if request.method=='POST':
		form=QuestionCreationForm(request.POST,request.FILES)
		form.instance.question_creator=request.user
		form.instance.question_exam=Exam_Object
		if form.is_valid():
			ques_ob=form.save()
			if questions:
				TotalMarks=Question.objects.filter(question_exam=Exam_Object).aggregate(Sum('question_mark'))
				Exam_Object.exam_marks=TotalMarks.get('question_mark__sum')
				Exam_Object.save() 
				print("OK")
				print(Exam_Object.pk)
				print(ques_ob.pk)
			return redirect('/question/'+str(ques_ob.pk)+'/option/create')
	form=QuestionCreationForm()
	context={'form':form,'questions':questions,'exam':Exam_Object}
	return render(request,'examonline/examdetails.html',context)

@login_required
@user_is_examcreator
def ExamEditView(request,pk):
	Exam_Object=Exam.objects.get(pk=pk)
	form=ExamCreateForm(request.POST or None,instance=Exam_Object)
	context={'form':form}
	if request.method=='POST':
		if form.is_valid():
			form.save()
			return redirect('/home/teacher')
	return render(request,'examonline/examedit.html',context)

@login_required
@user_is_examcreator
def ExamUpdate(request,pk):
	ExamObject=Exam.objects.get(pk=pk)
	questions=ExamObject.question_set.all()
	paginator=Paginator(questions,1)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	print(page_obj.number)
	q=paginator.page_range
	context={'q':q,'page_obj':page_obj,'questions':questions}
	return render(request,'examonline/examupdate.html',context)

@login_required
@user_is_examcreator
def ExamDeleteView(request,pk):
	Exam_Object=Exam.objects.get(pk=pk)
	context={'exam':Exam_Object}
	if request.method=='POST':
		Exam_Object.delete()
		return redirect('/home/teacher')
	return render(request,'examonline/examdelete.html',context)

@login_required
@user_is_teacher
def QuestionCreateView(request):
	if request.method=='POST':
		form=QuestionCreationForm(request.POST)
		return HttpResponse("Question Created")
	form=QuestionCreationForm()
	context={'form':form}
	return render(request,'examonline/questioncreate.html',context)

@login_required
@user_is_questioncreator
def QuestionEditView(request,pk):
	QuestionObject=Question.objects.get(pk=pk)
	Exam_Object=QuestionObject.question_exam
	Emarks=Exam_Object.exam_marks
	Qmark=QuestionObject.question_mark
	form=QuestionCreationForm(request.POST or None,request.FILES or None,instance=QuestionObject)
	if request.method=='POST':
		form=QuestionCreationForm(request.POST,request.FILES)
		form.instance.question_creator=request.user
		form.instance.question_exam=Exam_Object
		if form.is_valid():
			Exam_Object
			QuestionObject.question_image=(form.cleaned_data['question_image'])
			QuestionObject.question=(form.cleaned_data['question'])
			QuestionObject.question_negative=(form.cleaned_data['question_negative'])
			QuestionObject.question_mark=(form.cleaned_data['question_mark'])
			QuestionObject.save()
			Exam_Object.exam_marks=Emarks-Qmark+QuestionObject.question_mark
			Exam_Object.save()
			#ques_ob=form.save()
			return redirect('/exam/'+str(Exam_Object.pk)+'/update')
	context={'form':form,'ques':QuestionObject,'exam':Exam_Object}
	return render(request,'examonline/questionupdate.html',context)
@login_required
@user_is_questioncreator
def QuestionDeleteView(request,pk):
	QuestionObject=Question.objects.get(pk=pk)
	exam=QuestionObject.question_exam
	mark=exam.exam_marks
	qmark=QuestionObject.question_mark
	id=exam.pk
	context={'question':QuestionObject}
	if request.method=='POST':
		QuestionObject.delete()
		exam.exam_marks=mark-qmark
		exam.save()
		return redirect('/exam/'+str(id)+'/update')
	return render(request,'examonline/questiondelete.html',context)

@login_required
@user_is_questioncreator
def OptionCreateView(request,pk):
	print("in option")
	idd=pk
	print("In option ")
	Question_Object=Question.objects.get(pk=pk)

	if request.method=='POST':
		form=OptionCreationForm(request.POST)
		form.instance.question=Question_Object
		form.save()
		return redirect('/question/'+str(pk)+'/option/create')
	form=OptionCreationForm()
	options=Question_Object.option_set.all()
	context={'form':form,'question':Question_Object,'options':options}#,'ca_form':ca_form}
	return render(request,'examonline/optioncreate.html',context)

@login_required
@user_is_optioncreator
def TrueOption(request,pk):
	TrueOption=Option.objects.get(pk=pk)
	id=TrueOption.question.pk
	Question_Object=Question.objects.get(pk=id)
	Question_Object.option_set.all().update(option_status=False)
	TrueOption.option_status=True
	TrueOption.save()
	return redirect('/question/'+str(id)+'/option/create')

@login_required
@user_is_optioncreator
def OptionDeleteView(request,pk):
	OptionObject=Option.objects.get(pk=pk)
	id=OptionObject.question.pk
	OptionObject.delete()
	return redirect('/question/'+str(id)+'/option/create')

@login_required
@user_is_examcreator
def ExamPost(request,pk):
	ExamObject=Exam.objects.get(pk=pk)
	questions=Question.objects.filter(question_exam=ExamObject)
	qcount=questions.count()
	for q in questions:
		opt=q.option_set.all()
		optcount=opt.count()
		if(opt.exists()):
			if optcount<3:
				context={'optcount':optcount,'ques':q}
				return render(request,'examonline/fewoptions.html',context)
			if Option.objects.filter(question=q).filter(option_status=True).exists():
				pass
			else:
				context={'ques':q}
				return render(request,'examonline/examoptionsubmitfail.html',context)
		else:
			context={'ques':q}
			return render(request,'examonline/examsubmitfail.html',context)
	if (qcount<5):
		context={'qcount':qcount,'exampk':pk}
		return render (request,'examonline/fewquestions.html',context)
	ExamObject.exam_ready=True
	ExamObject.save()
	return redirect('/')

@login_required
@user_is_examcreator
def ExamPreviewPaginated(request,pk):
	ExamObject=Exam.objects.get(pk=pk)
	questions=ExamObject.question_set.all()
	paginator=Paginator(questions,1)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	print(page_obj.number)
	q=paginator.page_range
	context={'q':q,'page_obj':page_obj,'questions':questions}
	return render(request,'examonline/exampreviewpaginated.html',context)

@login_required
@user_is_examcreator
def AnswerPaper(request,pk,spk):
	ExamObject=Exam.objects.get(pk=pk)
	stud=User.objects.get(pk=spk)
	ExamStatusObject=ExamStatus.objects.filter(stud_name=stud).get(test=ExamObject)
	if ExamStatusObject.exam_status == False:
		raise PermissionDenied
	else:
		questions=ExamObject.question_set.all()
		Attempted=Candidate.objects.filter(stud_name=stud).filter(stud_exam=ExamObject)
		paginator=Paginator(questions,1)
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		print(page_obj.number)
		q=paginator.page_range
		try:
			StudOption=Candidate.objects.filter(stud_name=stud).get(stud_question=page_obj[0])
		except:
			StudOption=[]
		context={'paginator':paginator,'q':q,'page_obj':page_obj,'questions':questions,'attempted':Attempted,'studoption':StudOption}
		return render(request,'examonline/examsolutionpaginated.html',context)

@login_required
@user_is_examcreator
def Rank(request,pk):
	ExamObject=Exam.objects.get(pk=pk)
	students=ExamStatus.objects.filter(test=ExamObject).filter(exam_status=True).order_by('-exam_marks')
	c=students.count()
	for i in students:
		pass
	for i in range(0,c):
		if i == 0:
			students[i].rank=i+1
		elif i!=0 and students[i].exam_marks == students[i-1].exam_marks:
			students[i].rank=students[i-1].rank	
		else:
			students[i].rank=students[i-1].rank+1
		if(students[i].exam_marks >= ExamObject.exam_passmark):
			students[i].save()
		else:
			students[i].rank=-1
			students[i].save()
	context={'students':students}
	return render(request,'examonline/rank.html',context)

@login_required
@user_is_examcreator
def PassMark(request,pk):
	ExamObject=Exam.objects.get(pk=pk)
	if (request.method=='POST'):
		value=int(request.POST["pass"])
		ExamObject.exam_passmark=value
		ExamObject.save()

examonline/templates/examonline/alreadyattempted.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="d-flex justify-content-center">
	<h3>You have completed the exam : {{ExamStatusObject.test}}</h3>
</div>
<div class="d-flex justify-content-center"><h3> Score : {{ExamStatusObject.exam_marks}}/{{ExamStatusObject.test.exam_marks}}</h3>
</div>
<br>
	
<div class="d-flex justify-content-center">
	<button type='button' class="btn btn-info" > <a href="{% url 'solution-paginated' pk=ExamStatusObject.test.pk %}"style="color:White">View Anwers-Paginated View</a></button>
</div>
<br>
<div class="d-flex justify-content-center">
	<button type='button' class="btn btn-success" > <a href="{% url 'home-student' %}"style="color:White">Back to Home</a></button>
</div>

{% endblock %}

examonline/templates/examonline/exambase.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link href="css/main.css" rel="stylesheet" />
    
    <title>ExamGate</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </head>
  <body>
          
          {% block content %}
          {% endblock %}
       
  </body>
</html> 

examonline/templates/examonline/examdelete.html
{% extends 'accounts/base.html' %}
{% block content %}
	{% load crispy_forms_tags %}
	<br>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-7">
				<h3>Are you sure you want to delete the exam {{exam.exam_name}}</h3>
			<br>
			<form method="post">
				{% csrf_token %}
			<button type="submit" class="btn btn-danger">Yes,Delete </button>
			<a href="{% url 'exam-edit' pk=exam.pk %}"><button type="button" class="btn btn-success">No,Take Me Back</button></a>	
			</form>
			
			
		</div>
	</div></div>
	
{% endblock %}}

examonline/templates/examonline/examedit.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-7">
<form method="post">
{% csrf_token %}
{{form.instance.pk}}
{{form|crispy}}
<button class="btn btn-success" type="submit"> Update
	
</button>
</form>
<br>
<div>
<a href="{% url 'exam-delete' pk=form.instance.pk %}"><button class="btn btn-danger">Delete Exam</button></a>
</div>
</div>

{% endblock %}}

examonline/templates/examonline/examguidelines.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block content %}
	<div class="container-fluid  ">
			<br>
		<div class="row justify-content-center">

			<div class="card border-dark bg-light">
				<div class="card-header text-center">
					<h5 class="card-title">Exam : {{status.test}}</h5>
					<h5>Time Left :{{status.timeleft|intdiv:60}}:{{status.timeleft|mod:60}}</h5>
	
				</div>

					<ul>	
					<h6 class="text-danger"><li>Dont use browser  builtin buttons to navigate between questions.</li></h6>
				<h6 class="text-dark"><li>Only use
				<button type='button' class="btn-xs btn-info" ><span class="fas fa-angle-left"></span>  Prev Ques</button>
				<button type='button' class="btn-xs btn-info" >Next Ques  <span class="fas fa-angle-right"></span></button> Buttons or Question Palette to navigate</li></h6>
				
					<h6><li>In Question Palette</h6>
					<ul>
						<li>
					<button class=" btn-xs btn-outline-dark" >1</button>  Current Question<p></p>
						</li> 
						<li>
							<button class=" btn-xs	 btn-success" >1</button>   Answered    <p></p>
						</li>
						<li>
					<button class=" btn-xs btn-outline-success" >1</button>  Current Question and Answered<p></p>
						</li>
						<li>
					<button class=" btn" >1</button>  Not Answered
						</li>
					</ul>
				</li>
				<li><h6>Exam will be submitted automatically when time up</h6></li>
				<li>Use <button class=" btn-xs btn-primary" >Final Submit</button> to end exam when finished</li>
			</ul>
	
			<div class="card-footer text-center">
					<a href="{% url 'exam-attend' pk=exam.pk %} " target="_blank"><button class="btn btn-success" >Begin Exam</button> </a>
			
				
			</div>
		</div>
	</div>
{% endblock %}

examonline/templates/examonline/examoptionsubmitfail.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-7">
				<div class="d-flex justify-content-between">
					<div><h2 class="text-danger">ERROR</h2>
					</div>
					<div><button type='button' class="btn btn-info" > <a href="{% url 'option-create' pk=ques.pk %}"style="color:White">Go to Options Page</a></button>
					</div>
				</div>

<h4>True Option not set for the below Question</h4>
{% if ques.question %}                             
                {{ques.question}}
                <br>
                {% endif %}
              {% if ques.question_image %}                             
                <img src="{{ques.question_image.url}}" class="img-rounded">
                <br>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}}

examonline/templates/examonline/examslist.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
hr.thickline {
  border: 2px solid black;
  border-radius: 5px;
}
</style>
 		 
	<div class="container">
		<div class="d-flex flex-row-reverse bd-highlight">

  			<div class="p-2 bd-highlight"> 

  				<a href="{% url 'exam-create' %}"> <button class="btn btn-primary"><span class="fas fa-plus-circle"></span>
  			
NewExam</button> </a> </div>
			</div>
		<div class="row justify-content-center">
			<h2 >Exams - List</h2>
		
		</div>
		<div class="row justify-content-center">
			<div class="col">
				
				<table class="table table-bordered table-hover content-center">
					<thead>
						<tr class="text-center">
							<th>Name of Exam</th>
							<th>Duration</th>
							<th>Marks</th>
							<th>Pass Mark</th>
							<th>Preview/Edit</th>
							<th>Add Questions</th>
							<th>Students Attempted</th>
							<th>Exam Status</th>
							<th>Finish</th>

						</tr>
					</thead>
					{% for exams in postedexams %}
						<tr class="text-center">
							<td class="font-weight-normal"><a href="{% url 'exam-edit' pk=exams.pk %} "style="color:Black">{{ exams.exam_name}}</a> </td>
							<td>{{exams.exam_time}} Minutes</td>
							<td>{{exams.exam_marks}}</td>
								<td> <a href="{% url 'exam-pass' pk=exams.pk %}"style="color:Black"> {{exams.exam_passmark}} </a></td>
							
							<td><a href="{% url 'exam-pag-preview' pk=exams.pk %}"><button class="btn btn-outline-info">Preview</button></a></td>
							<td>--</td>
							<td> <a href="{% url 'exam-rank' pk=exams.pk %}"> <button class="btn btn-outline-success" >View Details</button> </a></td>
							<td class="font-weight-bold" style="color:green">Posted </td>
							<td>--</td>
						</tr>	
					{% endfor %}
					{% for exams in exams %}
						<tr class="text-center">
							<td class="font-weight-normal"><a href="{% url 'exam-edit' pk=exams.pk %} "style="color:Black">{{ exams.exam_name}}</a> </td>
							<td>{{exams.exam_time}} Minutes</td>
							<td>{{exams.exam_marks}}</td>
						<td> <a href="{% url 'exam-pass' pk=exams.pk %}"style="color:Black"> {{exams.exam_passmark}} </a></td>
							<td><a href="{% url 'exam-update' pk=exams.pk %}"><button class="btn btn-outline-info">Edit</button></a></td>
							<td><a href="{% url 'exam-details' pk=exams.pk %}"><button class="btn btn-outline-dark"><span class="fas fa-plus-circle"></span> Add Questions</button></a></td>
							<td>--</td>
							<td class="font-weight-bold" style="color:red">Pending </td>
							<td><a href="{% url 'exam-post' pk=exams.pk %}"><button class="btn btn-outline-success">Submit</button></a></td>
						</tr>
					{% endfor %}
				</table>	
			</div>
		</div>
	</div>
	
{% endblock %}

examonline/templates/examonline/studenthome.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block content %}

	<div class="container  ">
		<div class="row justify-content-center">
			<h2>List of Exams</h2>
		</div>
	
		<div class="row justify-content-center">

			<div class="col">

 				<table class="table table-bordered  text-center table-hover ">
 				<thead>

 					<tr>
 						<th>Exam</th>
 						<th>Max Marks</th>
 						<th>Pass Mark</th>
 						<th>Score</th>
 						<th>Rank</th>
 						<th>Duration (Min:Sec)</th>
 						<th>Status</th>
 					</tr>
 				</thead>
				<tbody>
				
					{% for pen in pending %}
				<tr>
					<td>{{pen.test}}</td>
					<td>{{pen.test.exam_marks}}</td>
					<td>{{pen.test.exam_passmark}} </td>
					<td>--</td>
					<td>--</td>
					<td>
			{{pen.timeleft|intdiv:60}}:{{pen.timeleft|mod:60}}
					</td>	
					<td><button type='button' class="btn btn-info" > <a href="{% url 'exam-guidelines' pk=pen.test.pk %}"style="color:White" >Resume </a></button></td>
				</tr>
				{% endfor %}
				{% for e in unattempted %}
				<tr>
					<td>{{e.exam_name}}</td>
					<td>{{e.exam_marks}}</td>
					<td>{{e.exam_passmark}}</td>
					<td>--</td>
					<td>--</td>
					<td>{{e.exam_time}}:0</td>
					<td><button type='button' class="btn btn-primary" > <a href="{% url 'exam-guidelines' pk=e.pk %} "style="color:White" >Attempt</a></button></td>
				</tr>
				{% endfor %}
			{% for c in completed %}
				<tr>
					<td>{{c.test}}</td>
					<td>{{c.test.exam_marks}}</td>
					<td>{{c.test.exam_passmark}}</td>
					<td>{{c.exam_marks}}</td>
					<td>
					{% if c.rank %}
					 {% if c.rank > 0  %}
						{{c.rank}}/{{c.test.examstatus_set.count}}
						{% else %}
						Not Qualified	
						{% endif %}
					{% else %}
						Rank will be Updated Soon
					{% endif %}
					</td>
					<td>--</td>
					<td><button type='button' class="btn btn-success" > <a href="{% url 'solution-paginated' pk=c.test.pk %}"style="color:White">AnswerKey</a></button></td>
				</tr>
				{% endfor %}	
				</tbody>
				</table>
			</div>
		</div>
	</div>
			{% endblock %}